### ISSUE TITLE
rgf.model

### ISSUE THREAD

**Issue by mglowacki100** [diefimov/otto_2015#3]
I had problem with running this model in RStudio. I don't remember the exact error message but it was related to tasks and workers. Solution from time perspective was easy - rebuild rgf 1.2 c++ library. 
I think you could put this as hint in documentation.

**Comment by diefimov** [comment]
rgf 1.2 in the folder is compiled under Mac, probably you use Linux of Windows, then you should recompile it. Thanks for the remark!
